advising_col2values = {
    ('area', 'AREA'): {'%software%', '%A%', '%hardware%',
                       '%software engineering%', '%artificial intelligence%'},
    ('course', 'ADVISORY_REQUIREMENT'): {'%A%',
                                         '%CS%',
                                         '%Core%',
                                         '%EECS%',
                                         '%chen%',
                                         '%core%',
                                         '%seminar%',
                                         '%software%'},
    ('course', 'COURSE_ID'): {'0',
                              '1',
                              '10',
                              '100',
                              '125',
                              '130',
                              '151',
                              '165',
                              '2015',
                              '2016',
                              '2017',
                              '2018',
                              '2019',
                              '203',
                              '214',
                              '240',
                              '270',
                              '280',
                              '281',
                              '285',
                              '3',
                              '300',
                              '370',
                              '373',
                              '376',
                              '381',
                              '388',
                              '398',
                              '4',
                              '400',
                              '445',
                              '482',
                              '483',
                              '484',
                              '485',
                              '489',
                              '492',
                              '494',
                              '496',
                              '498',
                              '5',
                              '500',
                              '545',
                              '595',
                              '598'},
    ('course', 'CREDITS'): {'3', '4', '5', '1', '10'},
    ('course', 'DEPARTMENT'): {'%A%',
                               '%CS%',
                               '%Core%',
                               '%EECS%',
                               '%chen%',
                               '%core%',
                               'CHEM',
                               'EECS',
                               'ENGR',
                               'MATH',
                               'PHYSICS',
                               'math'},
    ('course', 'DESCRIPTION'): {'%A%',
                                '%CS%',
                                '%CS-LSA%',
                                '%Core%',
                                '%EECS%',
                                '%MDE%',
                                '%Natural Language Processing%',
                                '%Smith%',
                                '%algorithms%',
                                '%artificial intelligence%',
                                '%chen%',
                                '%core%',
                                '%discrete math%',
                                '%hardware%',
                                '%jones%',
                                '%networks%',
                                '%operating systems%',
                                '%provost%',
                                '%seminar%',
                                '%smith%',
                                '%software engineering%',
                                '%software%',
                                '%video game%'},
    ('course', 'ENFORCED_REQUIREMENT'): {'%A%',
                                         '%CS%',
                                         '%Core%',
                                         '%EECS%',
                                         '%chen%',
                                         '%core%',
                                         'N / A'
                                         },
    ('course', 'HAS_DISCUSSION'): {'N', 'Y'},
    ('course', 'HAS_LAB'): {'N', 'Y'},
    ('course', 'NAME'): {'%A%',
                         '%CS%',
                         '%Core%',
                         '%EECS%',
                         '%Natural Language Processing%',
                         '%Smith%',
                         '%algorithms%',
                         '%artificial intelligence%',
                         '%autonomous robotics%',
                         '%chen%',
                         '%core%',
                         '%discrete math%',
                         '%introduction to artificial intelligence%',
                         '%networks%',
                         '%operating systems%',
                         '%seminar%',
                         '%smith%',
                         '%software engineering%',
                         '%software%',
                         '%video game%'},
    ('course', 'NUMBER'): {'100',
                           '125',
                           '130',
                           '151',
                           '165',
                           '203',
                           '214',
                           '240',
                           '270',
                           '280',
                           '281',
                           '285',
                           '300',
                           '370',
                           '373',
                           '376',
                           '381',
                           '388',
                           '398',
                           '400',
                           '445',
                           '482',
                           '483',
                           '484',
                           '485',
                           '489',
                           '492',
                           '494',
                           '496',
                           '498',
                           '500',
                           '545',
                           '595',
                           '598'},
    ('course', 'NUM_ENROLLED'): {'10',
                                 '100',
                                 '2015',
                                 '214',
                                 '3',
                                 '373',
                                 '496',
                                 '5'},
    ('course', 'NUM_REVIEWS'): {'3', '4', '5', '1', '10'},
    ('course', 'NUM_SEMESTERS'): {'3', '4', '5', '1', '10'},
    ('course_offering', 'ALLOW_AUDIT'): {'N'},
    ('course_offering', 'COURSE_ID'): {'0',
                                       '1',
                                       '10',
                                       '100',
                                       '125',
                                       '130',
                                       '151',
                                       '165',
                                       '2015',
                                       '2016',
                                       '2017',
                                       '2018',
                                       '2019',
                                       '203',
                                       '214',
                                       '240',
                                       '270',
                                       '280',
                                       '281',
                                       '285',
                                       '3',
                                       '300',
                                       '370',
                                       '373',
                                       '376',
                                       '381',
                                       '388',
                                       '398',
                                       '4',
                                       '400',
                                       '445',
                                       '482',
                                       '483',
                                       '484',
                                       '485',
                                       '489',
                                       '492',
                                       '494',
                                       '496',
                                       '498',
                                       '5',
                                       '500',
                                       '545',
                                       '595',
                                       '598'},
    ('course_offering', 'END_TIME'): {'08:00:00',
                                      '10:00:00',
                                      '12:00:00',
                                      '12:00',
                                      '10:00',
                                      '17:00:00'},
    ('course_offering', 'FRIDAY'): {'N', 'Y'},
    ('course_offering', 'HAS_FINAL_EXAM'): {'N'},
    ('course_offering', 'HAS_FINAL_PROJECT'): {'N'},
    ('course_offering', 'MONDAY'): {'N', 'Y'},
    ('course_offering', 'OFFERING_ID'): {'0',
                                         '1',
                                         '10',
                                         '100',
                                         '125',
                                         '130',
                                         '151',
                                         '165',
                                         '2015',
                                         '2016',
                                         '2017',
                                         '2018',
                                         '2019',
                                         '203',
                                         '214',
                                         '240',
                                         '270',
                                         '280',
                                         '281',
                                         '285',
                                         '3',
                                         '300',
                                         '370',
                                         '373',
                                         '376',
                                         '381',
                                         '388',
                                         '398',
                                         '4',
                                         '400',
                                         '445',
                                         '482',
                                         '483',
                                         '484',
                                         '485',
                                         '489',
                                         '492',
                                         '494',
                                         '496',
                                         '498',
                                         '5',
                                         '500',
                                         '545',
                                         '595',
                                         '598'},
    ('course_offering', 'SATURDAY'): {'N', 'Y'},
    ('course_offering', 'SECTION_NUMBER'): {'0',
                                            '1',
                                            '10',
                                            '100',
                                            '125',
                                            '130',
                                            '151',
                                            '165',
                                            '203',
                                            '214',
                                            '280',
                                            '285',
                                            '3',
                                            '300',
                                            '370',
                                            '373',
                                            '4',
                                            '400',
                                            '494',
                                            '5',
                                            '500'},
    ('course_offering', 'START_TIME'): {'08:00:00',
                                        '10:00:00',
                                        '12:00:00',
                                        '12:00',
                                        '10:00',
                                        '17:00:00'},
    ('course_offering', 'SUNDAY'): {'N', 'Y'},
    ('course_offering', 'THURSDAY'): {'N', 'Y'},
    ('course_offering', 'TUESDAY'): {'N', 'Y'},
    ('course_offering', 'WEDNESDAY'): {'N', 'Y'},
    ('instructor', 'INSTRUCTOR_ID'): {'0',
                                      '1',
                                      '10',
                                      '100',
                                      '125',
                                      '130',
                                      '151',
                                      '165',
                                      '2015',
                                      '2016',
                                      '2017',
                                      '2018',
                                      '2019',
                                      '203',
                                      '214',
                                      '240',
                                      '270',
                                      '280',
                                      '281',
                                      '285',
                                      '3',
                                      '300',
                                      '370',
                                      '373',
                                      '376',
                                      '381',
                                      '388',
                                      '398',
                                      '4',
                                      '400',
                                      '445',
                                      '482',
                                      '483',
                                      '484',
                                      '485',
                                      '489',
                                      '492',
                                      '494',
                                      '496',
                                      '498',
                                      '5',
                                      '500',
                                      '545',
                                      '595',
                                      '598'},
    ('instructor', 'NAME'): {'%A%',
                             '%CS%',
                             '%Core%',
                             '%MDE%',
                             '%Smith%',
                             '%brehob%',
                             '%chen%',
                             '%core%',
                             '%deorio%',
                             '%honglak lee%',
                             '%jones%',
                             '%kuipers%',
                             '%provost%',
                             '%smith%',
                             '%stout%',
                             '%peter chen%'
                             },
    ('instructor', 'UNIQNAME'): {'%A%',
                                 '%CS%',
                                 '%Core%',
                                 '%MDE%',
                                 '%Smith%',
                                 '%brehob%',
                                 '%chen%',
                                 '%core%',
                                 '%deorio%',
                                 '%jones%',
                                 '%kuipers%',
                                 '%smith%',
                                 '%stout%',
                                 '%quentin stout%',
                                 '%Quentin Stout%'
                                 },
    ('offering_instructor', 'INSTRUCTOR_ID'): {'0',
                                               '1',
                                               '10',
                                               '100',
                                               '125',
                                               '130',
                                               '151',
                                               '165',
                                               '2015',
                                               '2016',
                                               '2017',
                                               '2018',
                                               '2019',
                                               '203',
                                               '214',
                                               '240',
                                               '270',
                                               '280',
                                               '281',
                                               '285',
                                               '3',
                                               '300',
                                               '370',
                                               '373',
                                               '376',
                                               '381',
                                               '388',
                                               '398',
                                               '4',
                                               '400',
                                               '445',
                                               '482',
                                               '483',
                                               '484',
                                               '485',
                                               '489',
                                               '492',
                                               '494',
                                               '496',
                                               '498',
                                               '5',
                                               '500',
                                               '545',
                                               '595',
                                               '598'},
    ('offering_instructor', 'OFFERING_ID'): {'0',
                                             '1',
                                             '10',
                                             '100',
                                             '125',
                                             '130',
                                             '151',
                                             '165',
                                             '2015',
                                             '2016',
                                             '2017',
                                             '2018',
                                             '2019',
                                             '203',
                                             '214',
                                             '240',
                                             '270',
                                             '280',
                                             '281',
                                             '285',
                                             '3',
                                             '300',
                                             '370',
                                             '373',
                                             '376',
                                             '381',
                                             '388',
                                             '398',
                                             '4',
                                             '400',
                                             '445',
                                             '482',
                                             '483',
                                             '484',
                                             '485',
                                             '489',
                                             '492',
                                             '494',
                                             '496',
                                             '498',
                                             '5',
                                             '500',
                                             '545',
                                             '595',
                                             '598'},
    ('offering_instructor', 'OFFERING_INSTRUCTOR_ID'): {'0',
                                                        '1',
                                                        '10',
                                                        '100',
                                                        '125',
                                                        '130',
                                                        '151',
                                                        '165',
                                                        '2015',
                                                        '2016',
                                                        '2017',
                                                        '2018',
                                                        '2019',
                                                        '203',
                                                        '214',
                                                        '240',
                                                        '270',
                                                        '280',
                                                        '281',
                                                        '285',
                                                        '3',
                                                        '300',
                                                        '370',
                                                        '373',
                                                        '376',
                                                        '381',
                                                        '388',
                                                        '398',
                                                        '4',
                                                        '400',
                                                        '445',
                                                        '482',
                                                        '483',
                                                        '484',
                                                        '485',
                                                        '489',
                                                        '492',
                                                        '494',
                                                        '496',
                                                        '498',
                                                        '5',
                                                        '500',
                                                        '545',
                                                        '595',
                                                        '598'},
    ('program', 'COLLEGE'): {'EECS', '%EECS%', '%CS%'},
    ('program', 'NAME'): {'CS-LSA', '%A%', '%CS%', '%CS-LSA%'},
    ('program', 'PROGRAM_ID'): {'1'},
    ('program_course', 'CATEGORY'): {'%A%',
                                     '%CS%',
                                     '%Core%',
                                     '%MDE%',
                                     '%ULCS%',
                                     '%core%',
                                     'MDE',
                                     'PreMajor',
                                     'ULCS'},
    ('program_course', 'PROGRAM_ID'): {'1'},
    ('program_course', 'WORKLOAD'): {'4', '1', '3'},
    ('program_requirement', 'ADDITIONAL_REQ'): {'%A%'},
    ('program_requirement', 'CATEGORY'): {'%A%',
                                          '%CS%',
                                          '%Core%',
                                          '%MDE%',
                                          '%ULCS%',
                                          '%core%',
                                          'MDE',
                                          'PreMajor',
                                          'ULCS'},
    ('program_requirement', 'MIN_CREDIT'): {'3'},
    ('program_requirement', 'PROGRAM_ID'): {'1'},
    ('semester', 'SEMESTER'): {'FA', 'SS', 'SP', 'WN', 'SU', '%A%'},
    ('semester', 'YEAR'): {'2016', '2017', '2018', '2015'},
    ('student', 'DECLARE_MAJOR'): {'N', 'Y'},
    ('student', 'DEGREE'): {'%A%'},
    ('student', 'ENTERED_AS'): {'%A%'},
    ('student', 'FIRSTNAME'): {'Jane', '%A%'},
    ('student', 'LASTNAME'): {'%A%',
                              '%Smith%',
                              '%jones%',
                              '%smith%',
                              'Smith'},
    ('student', 'PROGRAM_ID'): {'1'},
    ('student', 'STUDENT_ID'): {'3', '4', '5', '1', '10'},
    ('student', 'TOTAL_CREDIT'): {'240'},
    ('student_record', 'EARN_CREDIT'): {'Y'},
    ('student_record', 'GRADE'): {'A', '%A%'},
    ('student_record', 'STUDENT_ID'): {'3', '4', '5', '1', '10'}
}

col2values = {'database/advising/advising.sqlite': advising_col2values}
